
package com.vanbilloen.competitieplanning.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "TabTAPI_Service", targetNamespace = "http://api.frenoy.net/TabTAPI", wsdlLocation = "https://api.vttl.be/?wsdl")
public class TabTAPIService
    extends Service
{

    private final static URL TABTAPISERVICE_WSDL_LOCATION;
    private final static WebServiceException TABTAPISERVICE_EXCEPTION;
    private final static QName TABTAPISERVICE_QNAME = new QName("http://api.frenoy.net/TabTAPI", "TabTAPI_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.vttl.be/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TABTAPISERVICE_WSDL_LOCATION = url;
        TABTAPISERVICE_EXCEPTION = e;
    }

    public TabTAPIService() {
        super(__getWsdlLocation(), TABTAPISERVICE_QNAME);
    }

    public TabTAPIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TABTAPISERVICE_QNAME, features);
    }

    public TabTAPIService(URL wsdlLocation) {
        super(wsdlLocation, TABTAPISERVICE_QNAME);
    }

    public TabTAPIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TABTAPISERVICE_QNAME, features);
    }

    public TabTAPIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TabTAPIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TabTAPIPortType
     */
    @WebEndpoint(name = "TabTAPI_Port")
    public TabTAPIPortType getTabTAPIPort() {
        return super.getPort(new QName("http://api.frenoy.net/TabTAPI", "TabTAPI_Port"), TabTAPIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TabTAPIPortType
     */
    @WebEndpoint(name = "TabTAPI_Port")
    public TabTAPIPortType getTabTAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.frenoy.net/TabTAPI", "TabTAPI_Port"), TabTAPIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TABTAPISERVICE_EXCEPTION!= null) {
            throw TABTAPISERVICE_EXCEPTION;
        }
        return TABTAPISERVICE_WSDL_LOCATION;
    }

}
