
package com.vanbilloen.competitieplanning.soap;

import java.math.BigInteger;
import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "TabTAPI_PortType", targetNamespace = "http://api.frenoy.net/TabTAPI")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TabTAPIPortType {


    /**
     * 
     * @param body
     * @return
     *     returns com.vanbilloen.competitieplanning.soap.TestResponse
     */
    @WebMethod(operationName = "Test", action = "Test")
    @WebResult(name = "TestResponse", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public TestResponse test(
        @WebParam(name = "TestRequest", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
        TestRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.vanbilloen.competitieplanning.soap.GetSeasonsResponse
     */
    @WebMethod(operationName = "GetSeasons", action = "GetSeasons")
    @WebResult(name = "GetSeasonsResponse", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetSeasonsResponse getSeasons(
        @WebParam(name = "GetSeasonsRequest", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
        GetSeasonsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.vanbilloen.competitieplanning.soap.GetClubTeamsResponse
     */
    @WebMethod(operationName = "GetClubTeams", action = "GetClubTeams")
    @WebResult(name = "GetClubTeamsResponse", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetClubTeamsResponse getClubTeams(
        @WebParam(name = "GetClubTeamsRequest", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
        GetClubTeamsRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.vanbilloen.competitieplanning.soap.GetDivisionRankingResponse
     */
    @WebMethod(operationName = "GetDivisionRanking", action = "GetDivisionRanking")
    @WebResult(name = "GetDivisionRankingResponse", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetDivisionRankingResponse getDivisionRanking(
        @WebParam(name = "GetDivisionRankingRequest", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
        GetDivisionRankingRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.vanbilloen.competitieplanning.soap.GetMatchesResponse
     */
    @WebMethod(operationName = "GetMatches", action = "GetMatches")
    @WebResult(name = "GetMatchesResponse", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetMatchesResponse getMatches(
        @WebParam(name = "GetMatchesRequest", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
        GetMatchesRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.vanbilloen.competitieplanning.soap.GetMembersResponse
     */
    @WebMethod(operationName = "GetMembers", action = "GetMembers")
    @WebResult(name = "GetMembersResponse", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetMembersResponse getMembers(
        @WebParam(name = "GetMembersRequest", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
        GetMembersRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.vanbilloen.competitieplanning.soap.UploadResponse
     */
    @WebMethod(operationName = "Upload", action = "Upload")
    @WebResult(name = "UploadResponse", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UploadResponse upload(
        @WebParam(name = "UploadRequest", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
        UploadRequest body);

    /**
     * 
     * @param body
     * @return
     *     returns com.vanbilloen.competitieplanning.soap.GetClubsResponse
     */
    @WebMethod(operationName = "GetClubs", action = "GetClubs")
    @WebResult(name = "GetClubsResponse", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetClubsResponse getClubs(
        @WebParam(name = "GetClubs", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
        GetClubs body);

    /**
     * 
     * @param body
     * @return
     *     returns com.vanbilloen.competitieplanning.soap.GetDivisionsResponse
     */
    @WebMethod(operationName = "GetDivisions", action = "GetDivisions")
    @WebResult(name = "GetDivisionsResponse", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetDivisionsResponse getDivisions(
        @WebParam(name = "GetDivisions", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
        GetDivisions body);

    /**
     * 
     * @param body
     * @return
     *     returns com.vanbilloen.competitieplanning.soap.GetTournamentsResponse
     */
    @WebMethod(operationName = "GetTournaments", action = "GetTournaments")
    @WebResult(name = "GetTournamentsResponse", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetTournamentsResponse getTournaments(
        @WebParam(name = "GetTournaments", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
        GetTournaments body);

    /**
     * 
     * @param body
     * @return
     *     returns com.vanbilloen.competitieplanning.soap.GetMatchSystemsResponse
     */
    @WebMethod(operationName = "GetMatchSystems", action = "GetMatchSystems")
    @WebResult(name = "GetMatchSystemsResponse", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetMatchSystemsResponse getMatchSystems(
        @WebParam(name = "GetMatchSystems", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
        GetMatchSystems body);

    /**
     * 
     * @param messageEntries
     * @param tournamentUniqueIndex
     * @param messageCount
     * @param credentials
     * @param success
     * @param unregister
     * @param serieUniqueIndex
     * @param playerUniqueIndex
     * @param notifyPlayer
     */
    @WebMethod(operationName = "TournamentRegister", action = "TournamentRegister")
    @RequestWrapper(localName = "TournamentRegister", targetNamespace = "http://api.frenoy.net/TabTAPI", className = "com.vanbilloen.competitieplanning.soap.TournamentRegister")
    @ResponseWrapper(localName = "TournamentRegisterResponse", targetNamespace = "http://api.frenoy.net/TabTAPI", className = "com.vanbilloen.competitieplanning.soap.TournamentRegisterResponse")
    public void tournamentRegister(
        @WebParam(name = "Credentials", targetNamespace = "http://api.frenoy.net/TabTAPI")
        CredentialsType credentials,
        @WebParam(name = "TournamentUniqueIndex", targetNamespace = "http://api.frenoy.net/TabTAPI")
        BigInteger tournamentUniqueIndex,
        @WebParam(name = "SerieUniqueIndex", targetNamespace = "http://api.frenoy.net/TabTAPI")
        BigInteger serieUniqueIndex,
        @WebParam(name = "PlayerUniqueIndex", targetNamespace = "http://api.frenoy.net/TabTAPI")
        List<BigInteger> playerUniqueIndex,
        @WebParam(name = "Unregister", targetNamespace = "http://api.frenoy.net/TabTAPI")
        Boolean unregister,
        @WebParam(name = "NotifyPlayer", targetNamespace = "http://api.frenoy.net/TabTAPI")
        Boolean notifyPlayer,
        @WebParam(name = "Success", targetNamespace = "http://api.frenoy.net/TabTAPI", mode = WebParam.Mode.OUT)
        Holder<Boolean> success,
        @WebParam(name = "MessageCount", targetNamespace = "http://api.frenoy.net/TabTAPI", mode = WebParam.Mode.OUT)
        Holder<BigInteger> messageCount,
        @WebParam(name = "MessageEntries", targetNamespace = "http://api.frenoy.net/TabTAPI", mode = WebParam.Mode.OUT)
        Holder<List<String>> messageEntries);

    /**
     * 
     * @param body
     * @return
     *     returns com.vanbilloen.competitieplanning.soap.GetPlayerCategoriesResponse
     */
    @WebMethod(operationName = "GetPlayerCategories", action = "GetPlayerCategories")
    @WebResult(name = "GetPlayerCategoriesResponse", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetPlayerCategoriesResponse getPlayerCategories(
        @WebParam(name = "GetPlayerCategories", targetNamespace = "http://api.frenoy.net/TabTAPI", partName = "body")
        GetPlayerCategories body);

}
